Add kill by surronding
mabdelaal86/djambi pull request #1
Opened 2024-02-29 23:36 UTC by Simondharcourt

Hello ! 
I saw your djambi project which I found amazing and wanted to contribute to the project.
Here is a suggestion to add the rule of the surronding of a chief.
Please let me know what you think of it.

2024-03-01 09:49 UTC, mabdelaal86 commented
Thanks a lot for the contribution. It is very appreciated.
I will review your PR as soon as possible.

2024-03-03 20:45 UTC, mabdelaal86 requested changes
I will review the surrounding rule, and may come back with other comments.

2024-03-03 20:45 UTC, mabdelaal86 commented on flutter/lib/models/party.dart
> +  bool get isActive => chief.isAlive && !chief.isSurrounded() && movableMembers.isNotEmpty;
I prefer keeping `isActive` property close to `isLost`, as the logic is very related.

2024-03-03 21:30 UTC, Simondharcourt commented on flutter/lib/models/member.dart
> +      continue;  // Cell is off the board, considered as not surrounded.
Yes, indeed

2024-03-04 17:27 UTC, Simondharcourt commented
> I will review the surrounding rule, and may come back with other comments.

Great, thanks for the review. I updated the code in consequence

2024-03-08 16:20 UTC, mabdelaal86 commented
I have reviewed the kill by surrounding rules, and played the game with your changes. I found many deviations between your implementation and the rules (based on my understanding).

The following is what stated regarding killing by surrounding in the document that you have added:

> The second great irony is that if a Leader becomes completely immobilized,
fully encircled by corpses either friend or foe that prevent him from moving, and does
not have a remaining Necromobile to rescue him by moving the surrounding dead to
a more favorable place of rest, he likewise perishes and is eliminated from the game.

> But the forces of a Leader who perishes by encirclement become satellites only
when a Leader first occupies the Labyrinth or already occupies it following the
encirclement. While waiting for devolution (transfer of control), the other players
have no ownership over the pieces of the encircled Leader.

So, I see the following deviations in your implementation:

1. If a Leader has a Necromobile, it is NOT considered encircled by corpses.
2. If a Leader encircled by corpses and doesn't have a Necromobile, he perishes (get killed).
3. Pieces of encircled Leader are controlled (or owned) by the Leader in the Maze (Labyrinth) or the first Leader occupies the Maze. 
4. While pieces are waiting for devolution (transfer of control), they can't be moved or killed (This part is from [Wikipedia](https://en.wikipedia.org/wiki/Djambi))

2024-03-12 21:22 UTC, Simondharcourt commented
Thank you for your review. I will apply some changes to correct it as soon as possible.

2024-12-26 19:04 UTC, mabdelaal86 commented
I will close this PR since it was open for so long. I have implemented this feature in a slightly different way. You are welcome to contribute if you would like to make changes to the current behavior.

2024-12-26 19:04 UTC, closed without merging

2024-12-27 16:12 UTC, Simondharcourt commented
Sure ! I also started a repository some time ago to play a variant of the game, but I lack a bit of inspiration on how to adapt the rules..  if you want to have a look on it, you would be the most welcome :)) on https://github.com/Simondharcourt/djambi6players
(I made this project because I have the board game at home, and i feel the game needs a little bit of adaptation of the rules to be more balance and dynamic.. but I did not find the right balance yet)

2024-12-27 20:11 UTC, mabdelaal86 commented
Looks nice!

Since my objective is to play the game on mobile screens, I don't have plans to support more than 4 players in my project. I'm also trying to stick to Jean Anesto's original rules.

Feel free to get inspired by any part of my project, and let me know if you need any help in yours.

There is also another implementation of the game that supports 3 to 8 players:
https://github.com/JamesFaix/Djambi-N